spring.application.name=springboot-kafka

##CONSUMER CONFIGURATIONS
spring.kafka.consumer.bootstrap-servers: localhost:9092
#to add multiple servers, add a comma and mention the next server ",localhost:9093"

spring.kafka.consumer.group: consumerGroup

# what to do if the offset does not exist
spring.kafka.consumer.auto-offset-reset: earliest   

spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# for json deserialization we will only change the value serialzer and not the key
spring.kafka.consumer.value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

#kafka consumer can deserialze all the classes from the following package
spring.kafka.consumer.properties.spring.json.trusted.packages = *


##PRODUCER CONFIGURATIONS
spring.kafka.producer.bootstrap-servers: localhost:9092
spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer